import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/native/Navbar";
import ScrollToTop from "@/components/native/ScrollToTop";
import Footer from "@/components/native/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />{" "}
        <div className=" -mt-16">
          <ScrollToTop />
        </div>
      </body>
    </html>
  );
}
